# Generated by Django 5.1.2 on 2024-10-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('fromCity', models.CharField(max_length=180)),
                ('toCity', models.CharField(max_length=180)),
                ('fromTitle', models.CharField(max_length=180)),
                ('toTitle', models.CharField(max_length=180)),
                ('salary', models.CharField(max_length=180)),
                ('education', models.CharField(max_length=180)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=180)),
            ],
        ),
    ]
