# Generated by Django 5.1.2 on 2024-10-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobilityAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementitem',
            name='notes',
            field=models.CharField(default='No notes', max_length=200),
        ),
    ]
