# Generated by Django 5.1.2 on 2024-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobilityAnalyzer', '0002_movementitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementitem',
            name='notes',
            field=models.CharField(default='No notes.', max_length=200),
        ),
    ]
